### ISSUE TITLE
get_user_availability and calendar_event_array issue

### ISSUE THREAD

**Issue by sej3506** [WinRb/Viewpoint#197] opened 2015-03-12 20:26 UTC
Hi, I'm sending an array of email addresses to get_user_availability. This appears to have all the busy times for all the emails, which is what I want.

When I convert with calendar_event_array like the ReadMe suggests you should, it only returns an array of events for the first email. I'd like an array with an array for the events of each email.

I haven't been able to break into the Viewpoint::EWS::SOAP::EwsSoapFreeBusyResponse item in order to get the rest.

Suggestions?

**Comment by zenchild** [comment] 2015-03-15 16:58
Duplicate of #170.

**Closed** 2015-03-31 19:29 UTC
