### ISSUE TITLE
Find for recurring calendar items

### ISSUE THREAD

**Issue by nemilya** [WinRb/Viewpoint#270] opened 2018-01-26 15:05 UTC
Is there any way to search for Recurring calendar items by begin/end pediod?

https://msdn.microsoft.com/en-us/library/office/dn727655(v=exchg.150).aspx#sectionSection0

Now they are missing if searching by `items_between`...

Thank!

**Comment by tobias--** [comment] 2018-05-28 12:37
As a workaround you can use `find_items` with `calendar_view` as described in this issue: https://github.com/WinRb/Viewpoint/issues/184#issuecomment-63967542

**Comment by paulvt** [comment] 2019-02-18 11:04
This seems to be a bug/regression? In Viewpoint 0.1.27 it used a `CalendarView` when calling `find_items` on a calendar folder which would expand this.  See also:
https://github.com/WinRb/Viewpoint/blob/1139abcb9d02661988badd69f4ac235b67fbd01c/lib/model/generic_folder.rb#L291 and
https://github.com/WinRb/Viewpoint/blob/1139abcb9d02661988badd69f4ac235b67fbd01c/lib/model/calendar_folder.rb#L60

Now this method just seems to have a copy-pasted version of what is in `GenericFolder`.  See also:
https://github.com/WinRb/Viewpoint/blob/e8fec4ab1af25fc128062cd96770afdb9fc38c68/lib/ews/types/generic_folder.rb#L106 and
https://github.com/WinRb/Viewpoint/blob/e8fec4ab1af25fc128062cd96770afdb9fc38c68/lib/ews/types/calendar_folder.rb#L10

**Comment by pcai** [comment] 2024-07-08 20:45
according to @paulvt this is resolved in #276

**Closed by pcai** 2024-07-08 20:45 UTC
